### ISSUE TITLE
테스트

### ISSUE THREAD

**Issue by museion25** [museion25/xn#1]
이슈관리

If you want to embed images, this is how you do it:
![2014-06-05 05 15 59](https://cloud.githubusercontent.com/assets/14246214/9830562/469a974c-596e-11e5-9bb1-a9e9bc7d2694.jpg)

![Image of Yaktocat](https://octodex.github.com/images/yaktocat.png)

**Comment by museion25** [comment]
나름 편하다!!!

**Comment by kangmj37** [comment]
test
